version: '3'
services:
  api:
    build: ./server
    ports:
      - "1323:1323"
    restart: always

  web:
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - api
    environment: 
      - NODE_ENV=production
    restart: always