version: '3'
services:
  session:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - backend
    expose:
      - 6379
    restart: on-failure

  api:
    build: ./server
    ports:
      - "1323:1323"
    restart: always

  web:
    build: ./client
    ports: 
      - "3000:3000"
    depends_on: 
      - api
    environment: 
      - NODE_ENV=production
    restart: always

volumes:
  redis: