version: "3"
services:
  session:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    networks:
      - backend
    expose:
      - 6379
    restart: always

  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - mariadb:/var/lib/mysql
    restart: always

  api:
    build: ./server
    ports:
      - "1323:1323"
    networks:
      - backend
    depends_on:
      - session
      - database
    restart: always

networks:
  backend:

volumes:
  redis:
  mariadb:
